services:
  app:
    build: .
    container_name: commission_app
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel-network

  mysql:
    image: mysql:8.0
    container_name: commission_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3308:3306"
    networks:
      - laravel-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: commission_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8086:80"         
    depends_on:
      - mysql
    networks:
      - laravel-network

  nginx:
    image: nginx:alpine
    container_name: commission_nginx
    ports:
      - "8092:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
